In [135]:
import pandas as pd

In [136]:
# Reading in csv
data = pd.read_csv("dataset2_full.txt", sep="\s+", skip_blank_lines=True, header=None)

In [137]:
# Taking first 3 rows (relevant header details) into a separate variable
header_info = data.iloc[:3, :]

In [138]:
# Dropping the header details to get the raw input data
data = data.drop([0, 1, 2])

In [139]:
# Dropping columns that have NaN
data = data.dropna(axis=1)

In [140]:
def get_headers():
    header_with_co = list(header_info.iloc[1, :])
    header_without_co = []
    for i in header_with_co:
        try:
            float(i)
        except:
            header_without_co.append(i)
            continue
    return header_with_co, header_without_co
header_with_coordinates, header_without_coordinates = get_headers()

In [141]:
data.columns = header_without_coordinates

In [142]:
def generate_coordinate_cols():
    for i in header_with_coordinates:
        if i in data.columns:
            head = "lon"
            head_col = i
        else:
            data[f"{head_col}_{head}"] = float(i)
            head = "lat"
    return data
updated_data = generate_coordinate_cols()

In [143]:
updated_data["days"] = updated_data["DD-HH"].apply(lambda x: x.split("-")[0])
updated_data["hours"] = updated_data["DD-HH"].apply(lambda x: x.split("-")[1])

In [144]:
updated_data

,DD-HH,DAWS,FSIM,FSMI,GILL,MCMU,RANK,TALO,WGRY,BRD,...,OTT_lon,OTT_lat,RES_lon,RES_lat,STJ_lon,STJ_lat,VIC_lon,VIC_lat,days,hours
3,01-01,20.03,21.46,14.37,11.45,10.54,12.56,20.33,6.61,3.99,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,01,01
4,01-02,17.46,18.68,12.26,11.01,8.68,12.58,9.99,5.25,3.41,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,01,02
5,01-03,14.93,16.72,7.67,4.78,5.62,7.61,7.75,4.36,1.91,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,01,03
6,01-04,29.52,24.03,14.83,12.16,9.77,10.5,16.11,8.35,4.58,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,01,04
7,01-05,30.24,46.44,55.88,73.54,38.84,496.13,44.85,19.62,21.5,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,01,05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,31-20,52.23,42.9,34.02,44.1,23.15,88.84,138.96,20.21,13.6,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,31,20
743,31-21,24.19,26.08,26.53,33.35,15.03,60.9,77.77,9.85,9.45,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,31,21
744,31-22,37.06,35.31,31.08,31.06,20.93,57.5,89.48,17.64,12.25,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,31,22
745,31-23,22.46,23.5,25.03,23.85,16.0,42.18,61.7,11.61,10.54,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,31,23
746,31-24,20.34,36.41,26.23,17.48,12.13,31.28,20.01,6.77,6.5,...,-75.55,45.4,-94.89,74.69,-52.68,47.6,-123.42,48.52,31,24

In [145]:
updated_data.to_csv("dataset2_full_cleaned.csv", index=False)